### ISSUE TITLE
Unable to build due to riptano/collectd GitHub repo dependency non-existent 

### ISSUE THREAD

**Issue by ericsmalling** [datastax/metric-collector-for-apache-cassandra#103]
Trying to build from main or `v0.3.5` tag, the parent pom.xml is trying to pull `https://github.com/riptano/collectd/releases/download/v${collectd.version}/insights-collectd-${collectd.version}.tar.gz` but that GitHub repo does not seem to exist any more.

**Comment by mamccorm** [comment]
+1

**Comment by ericsmalling** [comment]
Per discussion on the k8ssandra project discord, it appears that DataStax made `riptano/collectd` private at some time in the last few months due to an problematic push.  This means that this project can not be built.

Given that no builds have been done in 5 months now—and new ones are not possible—what is the path forward?

**Comment by ericsmalling** [comment]
Closing as this was migrated to https://github.com/datastax/collectd
