### ISSUE TITLE
demo docker-compose.yml references tlp stress image that is no longer available

### ISSUE THREAD

**Issue by grahamnscp** [datastax/metric-collector-for-apache-cassandra#16]
Noticed that the demo docker-compose.yml file has two stress entries in it that reference an image that no longer exists on docker hub:
docker-compose.yml:    image: thelastpickle/tlp-stress:latest

When commenting out these entries; stress and stress2 the demo compose starts up okay.

**Comment by tjake** [comment]
Thanks for the report. looking...

**Comment by tjake** [comment]
Hmm I don't have this issue https://hub.docker.com/r/thelastpickle/tlp-stress

Are you able to docker pull? What error do you get?
