### ISSUE TITLE
licensing question.

### ISSUE THREAD

**Issue by piengeng** [datastax/metric-collector-for-apache-cassandra#5]
hi, i noticed this is Apache 2.0 license (seems good for all to use), but the dashboard used seems to be using https://github.com/datastax/dse-metric-reporter-dashboards/blob/master/LICENSE.md as screenshots shown is very similar to datastax/dse-metric-reporter-dashboards. means the world should not use it unless paying datastax, so i'm confused how Apache 2.0 fits here...

**Comment by tjake** [comment]
Hi @piengeng 

The dashboards shown are local to this repo under `/dashboards` they are ASLv2
