### ISSUE TITLE
Is the docker-compose demo supposed to actually work?

### ISSUE THREAD

**Issue by pdehlke** [datastax/metric-collector-for-apache-cassandra#6]
pde@Clarence:src/github.com/datastax/metric-collector-for-apache-cassandra/dashboards/demo (master)$ docker-compose up
Creating demo_prometheus_1 ... done
Creating demo_grafana_1    ... done
Creating demo_cassandra_1  ... done

ERROR: for cassandra2  Container "f72b29055251" is unhealthy.
ERROR: Encountered errors while bringing up the project.

pde@Clarence:src/github.com/datastax/metric-collector-for-apache-cassandra/dashboards/demo (master)$ docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                     PORTS                    NAMES
f72b29055251        cassandra:3.11            "docker-entrypoint.s…"   5 seconds ago       Exited (1) 3 seconds ago                            demo_cassandra_1
40a18fda2908        prom/prometheus:v2.17.1   "/bin/prometheus --c…"   5 seconds ago       Up 3 seconds               0.0.0.0:9090->9090/tcp   demo_prometheus_1
d40b4861d1f4        grafana/grafana:5.3.2     "/run.sh"                5 seconds ago       Up 3 seconds               0.0.0.0:3000->3000/tcp   demo_grafana_1
pde@Clarence:src/github.com/datastax/metric-collector-for-apache-cassandra/dashboards/demo (master)$

**Comment by tjake** [comment]
Make sure you build the project first as mentioned in the demo/Readme.md

**Comment by pdehlke** [comment]
I see. So /README.md is wrong when it says:

## Try the demo
`docker-compose up` is all you need from the [dashboards/demo](dashboards/demo) directory to get a cluster with a light
workload and dashboards connected to kick the tires.

Thanks :)

**Comment by tjake** [comment]
Ah good find. I'll fix the docker-compose to build the project :)

**Comment by tjake** [comment]
Ok added in 1ba6e0f 
Docker compose up will build the agent then use it.
